version: '3.4'

services:
  yowsup:
    image: yowsup
    volumes:
      - /sharedfolders/NCData/yowsup:/root/.config/yowsup/
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5678:5678
